openapi: 3.0.3

info:
  title: Firestore Schemas
  version: 1.0.0
  description: Firestore のスキーマ定義

paths:
  /users_v1/{uid}:
    get:
      responses:
        "200":
          description: ユーザー情報
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true

  /conditions_v1/{documentId}:
    get:
      responses:
        "200":
          description: 体調などの主観的なコンディション
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  createdAtIso8601:
                    description: ISO8601形式の作成日時
                    type: string
                    example: 2004-04-01T12:00+09:00
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  subjectUid:
                    description: 対象者のUID
                    type: string
                  creatorType:
                    description: contentの作成者の種類
                    type: string
                    enum:
                      - user
                      - system
                  content:
                    description: コンディションの内容
                    type: object
                    oneOf:
                      - $ref: "#/components/schemas/ConditionContentEmpty"
                      - $ref: "#/components/schemas/ConditionContentText"
                      - $ref: "#/components/schemas/ConditionContentTextWithSearchKeywords"
                      - $ref: "#/components/schemas/ConditionContentImage"
                      - $ref: "#/components/schemas/ConditionContentAudio"

  /highlights_v1/{documentId}:
    get:
      responses:
        "200":
          description: 生成モデルが生成したハイライト
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  subjectUid:
                    description: ハイライトの対象のユーザーのUID
                    type: string
                  content:
                    description: ハイライトの内容
                    type: object
                    nullable: true
                    oneOf:
                      - $ref: "#/components/schemas/HighlightContentEmpty"
                      - $ref: "#/components/schemas/HighlightContentPrivate"
                      - $ref: "#/components/schemas/HighlightContentProfessional"

components:
  schemas:
    HighlightContentEmpty:
      required:
        - style
      properties:
        style:
          description: ハイライトのスタイル
          type: string
          default: empty

    HighlightContentPrivate:
      required:
        - style
        - startAt
        - period
        - subjectiveTrend
        - objectiveTrend
        - analysisResult
        - advice
        - abstract
        - state
      properties:
        style:
          description: ハイライトのスタイル
          type: string
          default: private
        startAt:
          description: ハイライトを作成開始する日時。この日からN日前のハイライト Timestamp
          type: object
        period:
          description: ハイライトの対象期間
          type: string
          default: past1day
          enum:
            - past1day
            - past7days
            - past14days
            - past21days
            - past28days
        subjectiveTrend:
          description: 主観的なデータのトレンド
          type: string
        objectiveTrend:
          description: 客観的なデータのトレンド
          type: string
        analysisResult:
          description: 分析結果
          type: string
        advice:
          description: アドバイス
          type: string
        abstract:
          description: 分析結果の要旨
          type: string
        state:
          description: 生成モデルでの処理の状態
          type: string
          default: pending
          enum:
            - pending
            - inProgress
            - success
            - failure
        promptFileUri:
          description: 生成モデルによるハイライトの生成プロンプトのファイルパス
          type: string
          example: gs://bucket/path/to/file
          nullable: true

    HighlightContentProfessional:
      required:
        - style
        - startAt
        - period
        - analysisResults
        - abstract
        - state
      properties:
        style:
          description: ハイライトのスタイル
          type: string
          default: professional
        startAt:
          description: ハイライトを作成開始する日時。この日からN日前のハイライト Timestamp
          type: object
        period:
          description: ハイライトの対象期間
          type: string
          default: past1day
          enum:
            - past1day
            - past7days
            - past14days
            - past21days
            - past28days
        analysisResults:
          description: 分析結果
          type: array
          items:
            type: string
        abstract:
          description: 分析結果の要旨
          type: string
        state:
          description: 生成モデルでの処理の状態
          type: string
          default: pending
          enum:
            - pending
            - inProgress
            - success
            - failure
        promptFileUri:
          description: 生成モデルによるハイライトの生成プロンプトのファイルパス
          type: string
          example: gs://bucket/path/to/file
          nullable: true

    ConditionContentEmpty:
      required:
        - type
      properties:
        type:
          description: コンディションの種類
          type: string
          default: empty

    ConditionContentText:
      required:
        - type
        - text
      properties:
        type:
          description: コンディションの種類
          type: string
          default: text
        text:
          description: 記録
          type: string
          example: 頭痛がする

    ConditionContentTextWithSearchKeywords:
      required:
        - type
        - text
        - searchKeywords
      properties:
        type:
          description: コンディションの種類
          type: string
          default: textWithSearchKeywords
        text:
          description: 記録
          type: string
          example: 頭痛がする
        searchKeywords:
          description: 検索キーワード
          type: array
          items:
            type: string
          example: [妊婦 頭痛, 妊婦 頭痛がする]

    ConditionContentImage:
      required:
        - type
        - attachments
      properties:
        type:
          description: コンディションの種類
          type: string
          default: image
        attachments:
          description: 添付ファイル
          type: array
          items:
            type: object
            required:
              - fileUri
              - mimeType
              - width
              - height
              - additionalInfo
            properties:
              fileUri:
                type: string
                description: 添付ファイルのgs://パス
                example: gs://bucket/path/to/file
              mimeType:
                type: string
                description: MIMEタイプ
                example: image/webp
              width:
                type: integer
                description: 画像の幅
                example: 1920
              height:
                type: integer
                description: 画像の高さ
                example: 1080
              additionalInfo:
                type: object
                description: その他の情報
                properties:
                  blurHash:
                    type: string
                    description: BlurHash
                    example: L6PZfSi_.AyE_3t7t7R**0o#DgR4

    ConditionContentAudio:
      required:
        - type
        - attachments
      properties:
        type:
          description: コンディションの種類
          type: string
          default: audio
        attachments:
          description: 添付ファイル
          type: array
          items:
            type: object
            required:
              - fileUri
              - mimeType
            properties:
              fileUri:
                type: string
                description: 添付ファイルのgs://パス
                example: gs://bucket/path/to/file
              mimeType:
                type: string
                description: MIMEタイプ
                example: audio/mpeg
