openapi: 3.0.3

info:
  title: Firestore Schemas
  version: 1.0.0
  description: Firestore のスキーマ定義

paths:
  /users_v1/{uid}:
    get:
      responses:
        "200":
          description: ユーザー情報
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  endOfDayReportTime:
                    description: 1日の終わりのレポートの作成目安時刻。UTC
                    type: object
                    properties:
                      hour:
                        description: 時
                        type: integer
                        example: 21
                      minute:
                        description: 分
                        type: integer
                        example: 0
                  weatherLocation:
                    description: 気象情報を取得する地域
                    type: string
                    nullable: true

  /conditions_v1/{documentId}:
    get:
      responses:
        "200":
          description: 体調などの主観的なコンディション
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  createdBy:
                    description: 作成者のUID
                    type: string
                  type:
                    description: コンディションの種類
                    type: string
                    default: unknown
                    enum:
                      - unknown
                      - subjective
                      - photo
                  attachments:
                    description: 添付ファイルのgs://パス
                    type: array
                    default: []
                    items:
                      type: string
                      example: gs://bucket/path/to/file
                  state:
                    description: attachmentsの解析で処理が必要な場合の状態
                    type: string
                    default: pending
                    enum:
                      - pending
                      - inProgress
                      - success
                      - failure
                  record:
                    description: 記録
                    type: string
                    example: 頭痛がする

  /reports_v1/{documentId}:
    get:
      responses:
        "200":
          description: 生成モデルが生成したレポート
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  subjectUid:
                    description: レポートの対象のユーザーのUID
                    type: string
                  startAt:
                    description: レポートを作成開始する日時。この日からN日前のレポート Timestamp
                    type: object
                  prompt:
                    description: 生成モデルによるレポート生成プロンプトのファイルパス
                    type: string
                    nullable: true
                    example: gs://bucket/path/to/file
                  type:
                    description: レポートの種類
                    type: string
                    default: past1day
                    enum:
                      - past1day
                      - past7days
                      - past14days
                      - past21days
                      - past28days
                  content:
                    description: レポートの内容
                    type: object
                    nullable: true
                    properties:
                      subjectiveConditionTendency:
                        description: 主観的な状態の傾向
                        type: string
                        nullable: true
                      objectiveConditionTendency:
                        description: 客観的な状態の傾向
                        type: string
                        nullable: true
                      analysisResult:
                        description: 分析結果
                        type: string
                        nullable: true
                      advice:
                        description: アドバイス
                        type: string
                        nullable: true
                  state:
                    description: 生成モデルでの処理の状態
                    type: string
                    default: pending
                    enum:
                      - pending
                      - inProgress
                      - success
                      - failure
