openapi: 3.0.3

info:
  title: Firestore Schemas
  version: 1.0.0
  description: Firestore のスキーマ定義

paths:
  /users_v1/{uid}:
    get:
      responses:
        "200":
          description: ユーザー情報
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  dailyHighlightTime:
                    description: 1日の終わりのハイライトの作成目安時刻。UTC
                    type: object
                    properties:
                      hour:
                        description: 時
                        type: integer
                        example: 21
                      minute:
                        description: 分
                        type: integer
                        example: 0
                  weatherLocation:
                    description: 気象情報を取得する地域
                    type: string
                    nullable: true

  /conditions_v1/{documentId}:
    get:
      responses:
        "200":
          description: 体調などの主観的なコンディション
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  createdBy:
                    description: 作成者のUID
                    type: string
                  type:
                    description: コンディションの種類
                    type: string
                    default: unknown
                    enum:
                      - unknown
                      - subjective
                      - photo
                  attachments:
                    description: 添付ファイルのgs://パス
                    type: array
                    default: []
                    items:
                      type: string
                      example: gs://bucket/path/to/file
                  state:
                    description: attachmentsの解析で処理が必要な場合の状態
                    type: string
                    default: pending
                    enum:
                      - pending
                      - inProgress
                      - success
                      - failure
                  record:
                    description: 記録
                    type: string
                    example: 頭痛がする

  /highlights_v1/{documentId}:
    get:
      responses:
        "200":
          description: 生成モデルが生成したハイライト
          content:
            application/json:
              schema:
                properties:
                  createdAt:
                    description: 作成日時 Timestamp
                    type: object
                    nullable: true
                  updatedAt:
                    description: 更新日時 Timestamp
                    type: object
                    nullable: true
                  deletedAt:
                    description: 削除日時 Timestamp
                    type: object
                    nullable: true
                  subjectUid:
                    description: ハイライトの対象のユーザーのUID
                    type: string
                  startAt:
                    description: ハイライトを作成開始する日時。この日からN日前のハイライト Timestamp
                    type: object
                  prompt:
                    description: 生成モデルによるハイライト生成プロンプトのファイルパス
                    type: string
                    nullable: true
                    example: gs://bucket/path/to/file
                  type:
                    description: ハイライトの種類
                    type: string
                    default: past1day
                    enum:
                      - past1day
                      - past7days
                      - past14days
                      - past21days
                      - past28days
                  style:
                    description: ハイライトのスタイル
                    type: string
                    default: private
                    enum:
                      - private
                      - professional
                  content:
                    description: ハイライトの内容
                    type: object
                    nullable: true
                    oneOf:
                      - $ref: "#/components/schemas/HighlightContentPrivate"
                      - $ref: "#/components/schemas/HighlightContentProfessional"
                  state:
                    description: 生成モデルでの処理の状態
                    type: string
                    default: pending
                    enum:
                      - pending
                      - inProgress
                      - success
                      - failure

components:
  schemas:
    HighlightContentPrivate:
      required:
        - style
        - subjectiveTrend
        - objectiveTrend
        - analysisResult
        - advice
        - abstract
      properties:
        style:
          description: ハイライトのスタイル
          type: string
          default: private
        subjectiveTrend:
          description: 主観的なデータのトレンド
          type: string
        objectiveTrend:
          description: 客観的なデータのトレンド
          type: string
        analysisResult:
          description: 分析結果
          type: string
        advice:
          description: アドバイス
          type: string
        abstract:
          description: 分析結果の要旨
          type: string

    HighlightContentProfessional:
      required:
        - style
        - analysisResults
        - abstract
      properties:
        style:
          description: ハイライトのスタイル
          type: string
          default: professional
        analysisResults:
          description: 分析結果
          type: array
          items:
            type: string
        abstract:
          description: 分析結果の要旨
          type: string
