name: blooms
description: "Body Log Observation and Outlook for Maternal State"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: 3.6.0
  flutter: 3.27.1

dependencies:
  adaptive_dialog: ^2.4.0
  clock: ^1.1.1
  cloud_firestore: ^5.6.1
  firebase_app_check: ^0.3.2
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_messaging: ^15.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.6.3
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  talker: ^4.6.1
  talker_dio_logger: ^4.6.1
  talker_flutter: ^4.6.1
  talker_riverpod_logger: ^4.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.3
  json_serializable: ^6.9.0
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  slang_build_runner: ^4.4.0
  test: any
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#3C8789"
  image: "../assets//icon/BLOOMS.png"
