name: blooms
description: "Body Log Observation and Outlook for Maternal State"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: 3.6.1
  flutter: 3.27.2

dependencies:
  adaptive_dialog: ^2.4.0
  budoux_dart: ^1.3.0
  cached_network_image: ^3.4.1
  clock: ^1.1.1
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2
  cupertino_calendar_picker: ^2.2.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.2
  firebase_analytics: ^11.4.2
  firebase_app_check: ^0.3.2
  firebase_auth: ^5.4.2
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.2
  firebase_storage: ^12.4.2
  firebase_ui_firestore: ^1.7.1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.8.2
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^4.1.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.8.0
  hooks_riverpod: ^2.6.1
  image: ^4.5.2
  image_picker: ^1.1.2
  intl: any
  json_annotation: ^4.9.0
  package_info_plus: ^8.2.1
  pull_down_button: ^0.10.2
  riverpod_annotation: ^2.6.1
  scrollview_observer: ^1.25.1
  shared_preferences: ^2.5.2
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  smooth_page_indicator: ^1.2.0+3
  super_context_menu: ^0.8.24
  talker: ^4.6.11
  talker_dio_logger: ^4.6.11
  talker_flutter: ^4.6.11
  talker_riverpod_logger: ^4.6.11
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.8.0
  json_serializable: ^6.9.0
  mockito: ^5.4.5
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  slang_build_runner: ^4.4.2
  test: any
  very_good_analysis: ^7.0.0
  widgetbook_generator: ^3.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/blooms.webp
    - assets/blooms_dark.webp

    - packages/budoux_dart/models/ja.json

flutter_native_splash:
  color: "#3C8789"
  color_dark: "#9ED094"
  image: "assets/blooms.png"
  image_dark: "assets/blooms_dark.png"
