// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK8RWudxw18JhvtyKzo5OxlsyjBCM_kI8',
    appId: '1:492016627549:web:a6b4b0c1588398211142b4',
    messagingSenderId: '492016627549',
    projectId: 'blooms-prod-43d74',
    authDomain: 'blooms-prod-43d74.firebaseapp.com',
    storageBucket: 'blooms-prod-43d74.firebasestorage.app',
    measurementId: 'G-7TY5VJRHN8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdkgWg-L06Rg-JdfvQQ5zKVamwTDlhqp8',
    appId: '1:492016627549:ios:8c389ddc0c9e9e531142b4',
    messagingSenderId: '492016627549',
    projectId: 'blooms-prod-43d74',
    storageBucket: 'blooms-prod-43d74.firebasestorage.app',
    iosBundleId: 'dev.kingu.BLOOMS',
  );

}