name: Firebase Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment"
        required: true
        options:
          - stg
          - prod

run-name: Firebase Deploy ${{ inputs.environment }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.environment }}
  cancel-in-progress: true

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ inputs.environment == 'prod' && vars.WORKLOAD_IDENTITY_PROVIDER_PROD || vars.WORKLOAD_IDENTITY_PROVIDER_STG }}
  SERVICE_ACCOUNT: ${{ inputs.environment == 'prod' && vars.SERVICE_ACCOUNT_PROD || vars.SERVICE_ACCOUNT_STG }}

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: deploy_only_extensions.sh
            useHotfixFirebaseCLI: true
          - script: deploy_only_hosting_app.sh
            flutterBuildScript: flutter_build_web_app.sh --flavor ${{ inputs.environment }}
          - script: deploy_only_hosting_widgetbook.sh
            flutterBuildScript: flutter_build_web_widgetbook.sh --flavor ${{ inputs.environment }}
          - script: deploy.sh

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2.0.0
        with:
          comment_on_pr: false

      - uses: actions/checkout@v4

      ### Setup Firebase CLI ###
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.7
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: firebase/functions/package.json

      - name: Firebase bootstrap
        if: ${{ matrix.useHotfixFirebaseCLI != 'true' }}
        run: |
          .github/workflows/firebase_bootstrap.sh

      - name: Firebase bootstrap (hotfix)
        if: ${{ matrix.useHotfixFirebaseCLI == 'true' }}
        run: |
          # バケット名が原因でデプロイできないのでHotfix版を使う
          # https://github.com/firebase/firebase-tools/issues/8152#issuecomment-2623374393
          gh repo clone KoheiKanagu/firebase-tools
          cd firebase-tools
          git checkout firebasestorage
          npm ci
          npm link
          npm ls -g --depth=0 --link=true

      - run: |
          firebase use ${{ inputs.environment }} --debug
        working-directory: firebase

      - name: Install dependencies
        if: ${{ matrix.flutterBuildScript == null }}
        working-directory: firebase/functions
        run: npm ci

      ### Setup Flutter ###
      - uses: kuhnroyal/flutter-fvm-config-action/config@v3
        if: ${{ matrix.flutterBuildScript != null }}
        id: fvm-config-action
        with:
          path: app/.fvmrc

      - name: Setup Flutter
        if: ${{ matrix.flutterBuildScript != null }}
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:"

      - name: Flutter bootstrap
        if: ${{ matrix.flutterBuildScript != null }}
        run: |
          .github/workflows/flutter_bootstrap.sh

      ### Flutter Build ###
      - name: Flutter Build
        if: ${{ matrix.flutterBuildScript != null }}
        run: |
          ./scripts/${{ matrix.flutterBuildScript }}
        working-directory: app
        env:
          USE_FVM: false

      ### Deploy ###
      - name: Firebase Deploy
        working-directory: firebase
        run: |
          ./scripts/${{ matrix.script }}
