name: Flutter Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/.fvmrc"
      - "app/pubspec.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-flutter_cache
  cancel-in-progress: true

jobs:
  cache:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action
        with:
          path: app/.fvmrc

      - name: Pods Cache
        if: ${{ runner.os == 'macOS' }}
        uses: actions/cache@v4.2.3
        with:
          path: |
            */ios/Pods
            ~/Library/Caches/CocoaPods/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: "beta"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:"

      - name: Flutter bootstrap
        run: |
          .github/workflows/flutter_bootstrap.sh

      - run: flutter pub get
        working-directory: app

      - name: Build iOS Config
        if: ${{ runner.os == 'macOS' }}
        working-directory: app
        env:
          USE_FVM: false
        run: |
          ./scripts/build-ios-config-only.sh --flavor stg