name: Pull Request

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-pull_request
  cancel-in-progress: true

jobs:
  changed-files:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      app_any_changed: ${{ steps.changed-files.outputs.app_any_changed == 'true' }}
      firebase_any_changed: ${{ steps.changed-files.outputs.firebase_any_changed == 'true' }}
      pubspec_any_changed: ${{ steps.changed-files.outputs.pubspec_any_changed == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files_yaml: |
            app:
              - app/**
            firebase:
              - firebase/**
            pubspec:
              - app/pubspec.yaml
              - app/pubspec.lock

  check_app:
    needs: changed-files
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - script: build_runner-build.sh
            os: ubuntu-latest
          - script: dart-analyze.sh
            os: ubuntu-latest
          - script: dart-fix.sh
            os: ubuntu-latest
          - script: dart-format.sh
            os: ubuntu-latest
          - script: test.sh
            os: ubuntu-latest
          - script: build-ios-config-only.sh --flavor stg
            os: macos-latest

    env:
      # 実行するかどうか
      # ubuntu-latestの場合はappディレクトリの変更がある時だけ実行
      # macos-latestの場合はpubspecの変更がある時だけ実行
      execute:
        (${{ matrix.os }} == "ubuntu-latest" && needs.changed-files.outputs.app_any_changed == 'true') ||
        (${{ matrix.os }} == "macos-latest" && needs.changed-files.outputs.pubspec_any_changed == 'true')

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        if: ${{ env.execute == 'true' }}
        with:
          comment_on_pr: false

      ### Set up ###
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ env.execute == 'true' }}
        with:
          persist-credentials: false

      - name: Pods Cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: ${{ env.execute == 'true' && runner.os == 'macOS' }}
        with:
          path: |
            */ios/Pods
            ~/Library/Caches/CocoaPods/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Update CocoaPods
        if: ${{ env.execute == 'true' && runner.os == 'macOS' }}
        run: gem update cocoapods

      - name: Verify CocoaPods Installation
        if: ${{ env.execute == 'true' && runner.os == 'macOS' }}
        run: pod --version

      - uses: kuhnroyal/flutter-fvm-config-action/config@0b792d004e2dfeda282a7af5c0609703658a9f8b # v3.1
        if: ${{ env.execute == 'true' }}
        id: fvm-config-action
        with:
          path: app/.fvmrc

      - name: Setup Flutter
        if: ${{ env.execute == 'true' }}
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: "beta"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:"

      - name: Flutter bootstrap
        if: ${{ env.execute == 'true' }}
        run: |
          .github/workflows/flutter_bootstrap.sh

      - name: Install dependencies
        if: ${{ env.execute == 'true' }}
        working-directory: app
        run: |
          dart pub get

      ### Run script ###
      - name: Configure git to ignore SPEC CHECKSUMS in Podfile.lock
        if: ${{ env.execute == 'true' && runner.os == 'macOS' }}
        run: |
          # pod installが実行された時、パスの違いなどでSPEC CHECKSUMSが変わるため、差分を無視する
          git config diff.ignore_spec_checksums.textconv "sed '/SPEC CHECKSUMS:/,\$d'"
          git config diff.ignore_spec_checksums.ignore all

      - name: Run script
        if: ${{ env.execute == 'true' }}
        working-directory: app
        run: |
          ./scripts/${{ matrix.script }}

          git diff --exit-code
        env:
          USE_FVM: false

  check_cloud_functions:
    needs: changed-files
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read

    env:
      execute: ${{ needs.changed-files.outputs.firebase_any_changed == 'true' }}

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        if: ${{ env.execute == 'true' }}
        with:
          comment_on_pr: false

      ### Setup ###
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        if: ${{ env.execute == 'true' }}
        with:
          persist-credentials: false

      - name: Authenticate to Google Cloud
        if: ${{ env.execute == 'true' }}
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_STG }}
          service_account: ${{ vars.SERVICE_ACCOUNT_STG }}

      - name: Setup Node.js environment
        if: ${{ env.execute == 'true' }}
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: firebase/functions/package.json

      - name: Firebase bootstrap
        if: ${{ env.execute == 'true' }}
        run: |
          .github/workflows/firebase_bootstrap.sh

      - name: Install dependencies
        if: ${{ env.execute == 'true' }}
        working-directory: firebase/functions
        run: npm ci

      ### Test ###
      - name: Test
        if: ${{ env.execute == 'true' }}
        working-directory: firebase
        run: |
          ./firebase_emulators_test.sh

  check_firebase:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      ### Setup ###
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_STG }}
          service_account: ${{ vars.SERVICE_ACCOUNT_STG }}

      - name: Setup Node.js environment
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: firebase/functions/package.json

      - name: Firebase bootstrap
        run: |
          .github/workflows/firebase_bootstrap.sh

      ### Check ###
      - name: Export Firestore indexes
        working-directory: firebase
        run: |
          ./scripts/export_firestore_indexes.sh

      - name: Export Firebase Extensions
        working-directory: firebase
        run: |
          ./scripts/export_extensions.sh

      - run: |
          git diff --exit-code
